gMonFrontPicTable = 0x0830a18c;
gMonPaletteTable = 0x08303678;

vanilla_can_use_item_check = 0x0803c230;
case_no_items_in_battle = 0x0803c23e;
ptr_to_vanilla_can_use_item_check = 0x803c0ac;

BuildStartMenuActions_Normal = 0x0809f4cc|1;


ptr1_to_gScriptCmdTable = 0x08098eb0;
ptr2_to_gScriptCmdTable = 0x08098f24;
ptr3_to_gScriptCmdTable = 0x08098f80;
ptr1_to_gScriptCmdTableEnd = 0x08098eb4;
ptr2_to_gScriptCmdTableEnd = 0x08098f28;
ptr3_to_gScriptCmdTableEnd = 0x08098f84;

gDummySpriteAnimTable = 0x082ec69c;
gDummySpriteAffineAnimTable = 0x082ec6a8;

ScrCmd_textcolor = ScrCmd_nop1;
ScrCmd_cmdc8 = ScrCmd_nop1;
ScrCmd_cmdc9 = ScrCmd_nop1;
ScrCmd_signmsg = ScrCmd_nop1;
ScrCmd_normalmsg = ScrCmd_nop1;
ScrCmd_comparehiddenvar = ScrCmd_nop1;
ScrCmd_setworldmapflag = ScrCmd_nop1;
Special_TradeEnemyMon = 0x0807F0E4|1;

